name: Deploy prod

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Version'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build with Gradle
      run: "ls -la"
