name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.0.1
      with:
        arguments: build
    
    - name: Upload generated artifact
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs/*.jar
        
  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v2
      with:
        name: Package
    - name: Deploy to EB
      run: "ls -la"
