name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.0.1
      with:
        arguments: build
    
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
        
    - name: machine echo folder
      run : "ls -la"
